### ISSUE TITLE
Install failed: when using the custom catalogsource on a cluster where Kuadarant operator was previously installed 

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#261]
**reproduce**

Install kuadrant via operatorhub
delete subscription to remove kuadrant
install kuadrant via custom catalog

observe subscription error 

```
lastTransitionTime: "2023-10-03T09:40:58Z"
    message: 'risk of data loss updating "ratelimitpolicies.kuadrant.io": new CRD
      removes version v1beta1 that is listed as a stored version on the existing CRD'
    reason: InstallComponentFailed
    status: "True"
    type: InstallPlanFailed 
```

**workaround / notes**

- You can remove the old CRDs and it will work then
- Not sure if this is an issue when upgrading rather than removing kuadrant first

**Comment by pehala** [comment]
This will arise for an upgrade and will most likely cause OperatorHub tests to fail as well.

**Comment by Boomatang** [comment]
In what use case would a user install Kuadrant via OperatorHub, then remove it and install it again via a custom catalog source? This does seem only like a something that would be done for development purposes.

Is the issue here that when removing the subscription to Kuadrant that all the resources related are not cleaned up correctly? Who should be responsible for this clean up? OLM or Kuadrant?

In the case for upgrades if there are any leftover CRDs, it would be up to Kuadrant to remove those CRD's. This can take two releases if there are migration requirements need before the removal of the CRD.  At no point in this upgrade scenario is the CRD orphaned.

**Comment by maleck13** [comment]
I think the issue @pehala is highlighting is that (based on the error message) we are removing a version in 1 release? So if operatorhub does and install and upgrade it will hit the same issue

**Comment by pehala** [comment]
The problem is that Kubernetes won't allow updating if there is no upgrade path between CRD versions, meaning if the definition existed before, it won't allow operator upgrade/install because there is no upgrade path between AuthPolicy v1 and v2. It is actually not bound to catalog sources at all.

Authorino got around this problem by having two API versions exist simultaneously through the webhook.

We hit it without having to try the actual upgrade because removing the operator does not remove the definitions (a feature, not a bug :D)

Trying out an actual upgrade is not trivial with non-released operators, I can try it out but I am 90% certain I will hit the same issue.

The easiest way to verify it really blocks the upgrade is creating PR to release this in the operator hub, as those have pretty robust upgrade tests for each operator and it caught a few similar issues for us before.

**Comment by maleck13** [comment]
In the immediate term we will  create a PR to the operator hub  to see is the upgrade required or optional cc @didierofrivia

**Comment by didierofrivia** [comment]
This issue was encountered in Operator Hub as well, the Policy CRDs v1beta1 were installed and there was no _convertion webhook_ in place to transform to the new version. However, since we decided to promote our bundles to _stable_ channel, the solution for this particular case was easier, just removing the directive `replaces`. Then the upgrade path chosen wasn't relying on any conversions from previous versions.

**Comment by maleck13** [comment]
I believe this can be closed now
