### ISSUE TITLE
TLSPolicy cannot be deleted if cert-manager is missing

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#419]
TLSPolicy gets stuck on its finalizer while deleting if cert-manager is not installed

**Comment by philbrookes** [comment]
@pehala is the finalizer added by cert-manager or something else adds it expecting cert-manager to remove it?

**Comment by mikenairn** [comment]
Closing this, re-open with steps to reproduce if it's still an issue.

If cert-manager was never installed this should never be possible [since]( https://github.com/Kuadrant/kuadrant-operator/pull/645/files#diff-38477e498c938e91320e277fd9be8bb1abfcbb26abc2af86c309865d49f19a3cR190), as the controller that adds the finalizer is never started.

If it happens after, cert-manager is removed after creating a Certificate, then that's a different issue that is likely cross component.
