### ISSUE TITLE
Switch to using LocalPolicyTargetReference struct instead

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadrant-operator#705]
From gateway api v1.1.0, the `PolicyTargetReference` struct that we were using had been removed but introduced several types of policy target references including `LocalPolicyTargetReference`:

- https://github.com/kubernetes-sigs/gateway-api/blob/690f754646e8326128fd686e3e46117ac479cfdf/apis/v1alpha2/policy_types.go#L34-L48

When we upgrade to use Gateway API v1.1.0, we shoudl consider using `LocalPolicyTargetReference` instead as it does not include the optional `namespace` field as we do not support setting the namespace field to any other the policy namespace.

This will remove the need for the cross namespace validation code in the policies:
- https://github.com/Kuadrant/kuadrant-operator/blob/d2e301b29fbff0b5b39edc487cf0e4d6a763b95e/api/v1alpha1/dnspolicy_types.go#L204-L206
- https://github.com/Kuadrant/kuadrant-operator/blob/main/api/v1alpha1/tlspolicy_types.go#L186-L188
- https://github.com/Kuadrant/kuadrant-operator/blob/d2e301b29fbff0b5b39edc487cf0e4d6a763b95e/api/v1beta2/authpolicy_types.go#L275-L277
- https://github.com/Kuadrant/kuadrant-operator/blob/d2e301b29fbff0b5b39edc487cf0e4d6a763b95e/api/v1beta2/ratelimitpolicy_types.go#L220-L222

**Comment by adam-cattermole** [comment]
Just as a side note here. gwapi v1.1.0 requires go 1.22 and also has conflicts with the pinned [maistra istio-operator version](https://github.com/Kuadrant/kuadrant-operator/blob/main/go.mod#L185) (because of it's dependence on the istio package).

I've started work on updating all of these parts here https://github.com/Kuadrant/kuadrant-operator/pull/696 but I was using the `NamespacedPolicyTargetReference` (as it was usable without any logic changes). I'll update this PR to use the `LocalPolicyTargetReference` as suggested here.
